"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['MagicExplorer.py']
DATA_FILES = ['sprites/grass.png', 'sprites/tree.png', 'sprites/axe.png',
'sprites/player.png', 'sprites/npc.png', 'sprites/water.png',
'sprites/boat.png', 'sprites/page.png', 'sprites/text_prompt.png',
'worlds/real_world.board', 'worlds/firstworld.board', 'fonts/Canterbury.ttf',
'fonts/Monospace.ttf']
OPTIONS = {'argv_emulation': True, 'packages': ['pygame', 'numpy']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
